# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

 gem "rails"
 gem "jobs"
 gem "json"


 #our gem file which lists which gems we are using
 